kind: pipeline
name: default

steps:
- name: test
  image: microsoft/dotnet:sdk
  commands:
    - dotnet test

- name: publish
  image: plugins/docker
  settings:
    repo: registry.mikelk.dk/beehive
    tags: latest