kind: pipeline
name: default

steps:
- name: test
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  commands:
    - dotnet test

- name: hub  
  image: plugins/docker
  settings:
    repo: mikaelelkiaer/beehive
    tags: latest
    username: mikaelelkiaer
    password:
      from_secret: password

---
kind: secret
name: password
data: Bqg4Fd/BTvzoej3dal+ddQHVoxY1KlM5Al2HBlSAWigNnIPutyeEEpdD6QhvCD+lZsm9QA9Gv5uKe0InnqaAPQ==
